spring.application.name=moneytree_back

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/moneytreedb
spring.datasource.username=moneytree
spring.datasource.password=moneytree

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB

moneytree_back.upload.path=upload

# ?? API
deposit.api.key = 8940f1b95dfb2066b422bcd1c75f74ab
deposit.api.base-url = https://finlife.fss.or.kr/finlifeapi/depositProductsSearch.json

# ?? API
saving.api.key = 8940f1b95dfb2066b422bcd1c75f74ab
saving.api.base-url = https://finlife.fss.or.kr/finlifeapi/savingProductsSearch.json